version: "3.7"

services:
 

  node_db:
    container_name: pg2
    image: postgres:14.1-alpine
    env_file:
      - ./.env
    ports:
      - "15001:5432"
    volumes:
      - pg2_data:/var/lib/postgresql/data

volumes:
  node_db:
  
