version: "3.7"

services:
 
  node_db:
    container_name: mongo
    image: 'bitnami/mongodb:latest'
    restart: always
    ports:
      - '27017:27017'
    env_file:
      - ./.env
    volumes:
      - node_db_data:/data/db

  node_db2:
    container_name: pg2
    image: postgres:14.1-alpine
    env_file:
      - ./.env
    ports:
      - "15001:5432"
    volumes:
      - pg2_data:/var/lib/postgresql/data

volumes:
  node_db:
  node_db2:
